// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test.Data;

#nullable disable

namespace test.Migrations
{
    [DbContext(typeof(DbContextPropiedad))]
    [Migration("20220531171618_addingdata")]
    partial class addingdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("test.Propetario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Propetario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Perez",
                            Name = "Fulano"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Perez",
                            Name = "Fulano"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Perez",
                            Name = "Fulano"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Perez",
                            Name = "Fulano"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
